server:
    port: 8080

spring:
  datasource:
    url: jdbd:mysql://localhost:3306/commerce_database
    username: commerceuser
    password: CommerceBank1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Commerce-Bank
